### ISSUE TITLE
简短而优雅的JS代码

### ISSUE THREAD

**Issue by Wellaiyo** [Wellaiyo/notes#50]
很多时候所谓奇淫技巧的JS代码不失为一种好的选择。因为相对于代码的晦涩，代码量更能给人增加阅读成本

#### 优雅的取整
```javascript
var a = ~~2.33
var b= 2.33 | 0
var c= 2.33 >> 0
```
![](https://camo.githubusercontent.com/4477c1325f5fd62cfc9fd75c0526cb93538ef07f/68747470733a2f2f7773342e73696e61696d672e636e2f6c617267652f303036744b6654636779316669706371636f6c6c786a3330387a3035673734652e6a7067)

#### 优雅的实现金钱格式化
正则实现
```javascript
var test1 = '1234567890'
var format = test1.replace(/\B(?=(\d{3})+(?!\d))/g, ',')

console.log(format)  // 1,234,567,890
```
```javascript
(23333333).toLocaleString('en-US')  // "23,333,333"
```
非正则实现
```javascript
function formatCash(str) {
  return str.split('').reverse().reduce((prev, next, index) => {
    return ((index % 3) ? next : (next + ',')) + prev
  })
}
console.log(formatCash('1234567890'))  // 1,234,567,890
```

#### 实现标准JSON的深拷贝
```javascript
var a = {
  a: 1,
  b: { c: 1, d: 2 }
}
var b=JSON.parse(JSON.stringify(a))
```

#### 实现数组去重
```javascript
[...new Set([1, "1", 2, 1, 1, 3])]
```
![](https://camo.githubusercontent.com/3a2026641f39fac1f34eee7e03ebe4a4b2d2f427/68747470733a2f2f7773322e73696e61696d672e636e2f6c617267652f303036744b6654636779316669706563633166746b6a33306136303374676c722e6a7067)

#### 取出一个数组中的最大值和最小值
```javascript
var numbers = [5, 458 , 120 , -215 , 228 , 400 , 122205, -85411]
var maxInNumbers = Math.max.apply(Math, numbers)
var minInNumbers = Math.min.apply(Math, numbers)
```
![](https://camo.githubusercontent.com/8532f719758da0730cc7821cb08abe52e774f687/68747470733a2f2f7773332e73696e61696d672e636e2f6c617267652f303036744b665463677931666970656c62397279376a3330647430363271336a2e6a7067)

#### 将argruments对象转换成数组
```javascript
var argArray = Array.prototype.slice.call(arguments)
// 或者ES6：
var argArray = Array.from(arguments)
```

#### 让JS脚本永远不报错
```javascript
window.onerror = function (m, f, l) { return true }
```

#### 对调两个数字的变量值
```javascript
let a = 1, b = 2
// 只能处理数字
[a, b] = [b, a]
```

#### 利用 CSS 的 content 属性 attr 抓取资料
![](https://camo.githubusercontent.com/5b75e16df7cb178731d2a16aaea417415167fef9/68747470733a2f2f7773332e73696e61696d672e636e2f6c617267652f303036744e633739677931666a76773869387377736a3330397030357a337a632e6a7067)
```html
<div data-msg="Open this file in Github Desktop">hover</div>
```
```css
div {
  width:100px;
  border:1px solid red;  
  position:relative;
}
div:hover:after {
  content:attr(data-msg);
  position:absolute;
  font-size: 12px;
  width:200%;
  line-height:30px;
  text-align:center;
  left:0;
  top:25px;
  border:1px solid green;
}
```

#### 使用属性选择器选择空链接
```css
a[href^="http"]:empty::before {
  content: attr(href);
}
```

#### CSS模拟打字的动画
```html
<h1>This is hello world !</h1>
```
```css
h1{
  font: bold 200% Consolas, Monaco, monospace;
  border-right: .1em solid;
  width: 16.5em; /* fallback */
  width: 20ch; /* # of chars */
  margin: 2em 1em;
  white-space: nowrap;
  overflow: hidden;
  animation: typing 10s steps(20,end) 2 , blink .5s step-end infinite alternate;
}
@keyframes typing { from { width: 0; } }
@keyframes blink { 50% { border-color: transparent; } }
```
