### ISSUE TITLE
Web移动端开发

### ISSUE THREAD

**Issue by Wellaiyo** [Wellaiyo/notes#65]
> [支付宝移动Web解决方案](http://am-team.github.io/about/about.html)

#### 页面宽度自动调整到设备宽度

```html
<meta name="viewport" content="width=device-width,initial-scale=1.0,minimum-scale=1.0,maximum-scale=1.0,user-scalable=no" />

```

#### 忽略系统自动识别

```html
<meta name="format-detection" content="telephone=no" />
<meta name="format-detection" content="email=no" />
```

#### 添加到主屏幕快速启动方式（仅针对ios的safari有效）

```html
<meta name="apple-mobile-web-app-status-bar-style" content="black" />
<!-- 可选default、black、black-translucent -->
```

#### 定义字体font-family

```css
/* 中文字体使用系统默认，英文用Helvetica */
/* 移动端定义字体的代码 */
body{font-family:Helvetica;}
```

#### 定义font-size

- 第一方案 `rem`
- 第二方案 `flex-box`（较第一方案更合理，因为正文的字体常用的为14px或者16px，如果在这个手机字号是15.5px，在另外一个手机又变成了14.9px，这样可能会有点奇怪）

媒体查询配置参考：

```css
html{font-size:10px}
@media screen and (min-width:321px) and (max-width:375px){html{font-size:11px}}
@media screen and (min-width:376px) and (max-width:414px){html{font-size:12px}}
@media screen and (min-width:415px) and (max-width:639px){html{font-size:15px}}
@media screen and (min-width:640px) and (max-width:719px){html{font-size:20px}}
@media screen and (min-width:720px) and (max-width:749px){html{font-size:22.5px}}
@media screen and (min-width:750px) and (max-width:799px){html{font-size:23.5px}}
@media screen and (min-width:800px){html{font-size:25px}}
```

#### Click屏幕产生200-300ms的延迟响应

出现这种问题的原因在于操作系统带给的双击缩放功能，判断是单击还会双击，需要捕获第一次单击后先Hold一段时间。

[fastclick](https://github.com/ftlabs/fastclick)、`zepto`的tap事件均可以解决该问题，或者绑定`ontouchstart`事件来响应。

#### 优化Retina屏上的图片

Retina拥有更多的像素点，导致图片可能会模糊。解决办法是保证图片长宽为偶数，且使用2倍图。

#### CSS基础样式重置优化

```css
// 去除元素被触摸产生的半透明灰色遮罩
a,button,input,textarea {
  -webkit-tap-highlight-color: rgba(0,0,0,0);
}
// 重置webkit表单元素的默认外观
button,input,textarea {
  -webkit-appearance: none;
  appearance: none;
}
// 重设webkit表单输入框placeholder颜色
input::-webkit-input-placeholder {
  color: #AAAAAA;
}
input:focus::-webkit-input-placeholder {
  color: #EEEEEE;
}
// 禁止长按触发系统事件
* {
  -webkit-touch-callout: none
}
// 去除Android上input的语音输入按钮
input::-webkit-input-speech-button {
  display: none
}
```

#### 判断屏幕旋转

```javascript
window.onorientationchange = () => {
  switch (window.orientation) {
    case -90: console.log(window.orientation)
      break
    case 90: console.log('横屏: ' + window.orientation)
      break
    case 0: console.log(window.orientation)
      break
    case 180: console.log('竖屏: ' + window.orientation)
      break
  }
}
```

```css
// media检测竖屏
@media all and (orientation: portrait) {
}
// media检测横屏
@media all and (orientation: landscape) {
}
```

#### 消除transition闪屏

```css
.transition-base {
  /* 设置内嵌的元素在 3D 空间如何呈现：保留 3D */
  -webkit-transform-style: preserve-3d;
  /* （设置进行转换的元素的背面在面对用户时是否可见：隐藏） */
  -webkit-backface-visibility: hidden;
}
```

#### 开启硬件加速

```css
.animate-better {
  -webkit-transform: translate3d(0, 0, 0);
  -moz-transform: translate3d(0, 0, 0);
  -ms-transform: translate3d(0, 0, 0);
  transform: translate3d(0, 0, 0);
}
```

#### 取消ios input输入英文首字母的默认大写和自动修正

```html
<input autocapitalize="off" autocorrect="off" />
```

#### fixed属性bug

ios下fixed元素容易定位出错，软键盘弹出时，影响fixed元素定位。

iOS下整个页面用iscroll模拟滚动条，然后absolute完成fixed效果；Android下直接使用position: fixed。参考：[移动端web页面使用position:fixed问题总结](https://github.com/maxzhang/maxzhang.github.com/issues/2)
